# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, inputs, ... }:

{
  boot.kernelPatches = let
    patchesDir = "${inputs.bore-scheduler-src}/patches/testing/linux-${lib.versions.majorMinor config.boot.kernelPackages.kernel.version}-bore";
  in
    lib.mapAttrsToList (name: _: {
      name = "bore-${name}";
      patch = "${patchesDir}/${name}";
    }) (builtins.readDir patchesDir);
}
