[env]
SUDO_ASKPASS = './askpass.nu'

[tasks.build]
run = 'nixos-rebuild build --impure --flake .#nixos'

[tasks.b]
run = 'mise build'

[tasks.switch-home]
run = 'home-manager switch --flake ./#user'

[tasks.hs] # sh is already taken
run = 'mise switch-home'

[tasks.test-desktop]
run = './rebuild.nu test desktop'

[tasks.test-gaming]
run = './rebuild.nu test gaming'

[tasks.test-server]
run = './rebuild.nu test server'

[tasks.td]
run = 'mise test-desktop'

[tasks.tg]
run = 'mise test-gaming'

[tasks.ts]
run = 'mise test-server'

[tasks.switch]
run = 'sudo -A nixos-rebuild switch --impure --flake .#nixos'

[tasks.switch-desktop]
run = './rebuild.nu switch desktop'

[tasks.switch-gaming]
run = './rebuild.nu switch gaming'

[tasks.switch-server]
run = './rebuild.nu switch server'

[tasks.sd]
run = 'mise switch-desktop'

[tasks.sg]
run = 'mise switch-gaming'

[tasks.ss]
run = 'mise switch-server'

[tasks.boot]
run = 'sudo -A nixos-rebuild boot --impure --flake .#nixos'
